HealthHub/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Clinics.urls")),
    path('user/', include("Users.urls")),
    path('medicalrecords/', include("Medicalrecords.urls")),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout', views.logout, name="logout"),
    path('profile', views.profile, name="profile"),
    path('medecin_details/<int:id>/',
         views.medecin_details, name='medecin_details'),
]

Users/models.py
from django.db import models

from Clinics.models import *


# Create your models here.


class User(models.Model):
    prenom = models.CharField(max_length=255)
    nom = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)
    tele = models.CharField(max_length=20, blank=True)
    role = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.username


class Admin(User):
    # define role as admin
    def __init__(self, *args, **kwargs):
        super(Admin, self).__init__(*args, **kwargs)
        self.role = 'admin'


def upload_to(instance, filename):
    user_name = instance.nom
    new_filename = f"{user_name}.jpg"
    return f"media/medecin_images/{new_filename}"


class Medecin(User):
    SPECIALITES_CHOICES = [
        ('cardiology', 'Cardiology'),
        ('dermatology', 'Dermatology'),
        ('gastroenterology', 'Gastroenterology'),
        ('neurology', 'Neurology'),
        ('oncology', 'Oncology'),
        ('ophthalmology', 'Ophthalmology'),
        ('pediatrics', 'Pediatrics'),
        ('psychiatry', 'Psychiatry'),
        ('urology', 'Urology'),
        ('others', 'Others'),
    ]
    specialite = models.CharField(max_length=255, choices=SPECIALITES_CHOICES)
    clinique = models.ForeignKey(Clinique, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_to, blank=True)
    description = models.TextField()
    address = models.CharField(max_length=255)
    jours_disponible = models.CharField(max_length=255)
    heure_disponible = models.CharField(max_length=255)

    # define role as medecin
    def __init__(self, *args, **kwargs):
        super(Medecin, self).__init__(*args, **kwargs)
        self.role = 'medecin'
        #  Modify the filename here so that it includes the user "nom"  exemple: "nom.jpg"


class Secretaire(User):
    clinique = models.ForeignKey(Clinique, on_delete=models.CASCADE)
    # define role as secretaire

    def __init__(self, *args, **kwargs):
        super(Secretaire, self).__init__(*args, **kwargs)
        self.role = 'secretaire'


class Patient(User):
    # sexe choices
    SEXE_CHOICES = [
        ('H', 'Homme'),
        ('F', 'Femme'),
    ]

    address = models.CharField(max_length=255, blank=True)
    sexe = models.CharField(max_length=255, choices=SEXE_CHOICES, blank=True)
    date_naissance = models.DateField(blank=True, null=True)

    # define role as patient
    def __init__(self, *args, **kwargs):
        super(Patient, self).__init__(*args, **kwargs)
        self.role = 'patient'

Users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse

# Face-recognitions
import cv2
import numpy as np
import face_recognition
import os


# Create your views here.

from Clinics.models import Clinique
from .models import *


############ Logout form Session ############
def logout(request):
    try:
        del request.session['USER']
    except:
        return redirect('login')
    return redirect('home')
############ end Logout form Session ############


# ############ Face-recognitions login ############

def face_login(user):
    path = 'media/medecin_images'
    images = []
    classNames = []

    for cl in os.listdir(path):
        curImg = cv2.imread(os.path.join(path, cl))
        images.append(curImg)
        classNames.append(os.path.splitext(cl)[0])

    def findEncodings(images):
        encodeList = []
        for img in images:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            encode = face_recognition.face_encodings(img)[0]
            encodeList.append(encode)
        return encodeList

    encodeListKnown = findEncodings(images)

    cap = cv2.VideoCapture(0)
    k = 0

    # while try 5 times
    nbr_try = 0
    while nbr_try < 5:
        nbr_try += 1
        success, img = cap.read()
        # img = captureScreen()
        imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)
        imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

        facesCurFrame = face_recognition.face_locations(imgS)
        encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)

        for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
            matches = face_recognition.compare_faces(
                encodeListKnown, encodeFace)
            faceDis = face_recognition.face_distance(
                encodeListKnown, encodeFace)
            print(faceDis)
            matchIndex = np.argmin(faceDis)

            if matches[matchIndex]:
                name = classNames[matchIndex].upper()
                y1, x2, y2, x1 = faceLoc
                # multiply by 4 to get the original size of the image
                y1, x2, y2, x1 = y1*4, x2*4, y2*4, x1*4
                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.rectangle(img, (x1, y2-35), (x2, y2),
                              (0, 255, 0), cv2.FILLED)
                cv2.putText(img, name+", Allowed", (x1+6, y2-6),
                            cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
                print(name)
                cv2.imshow('Login', img)
                k = cv2.waitKey(1) & 0xFF

                # print(k)
                if name == user.upper():
                    # close the webcam
                    cv2.destroyAllWindows()
                    return True

                if nbr_try == 5:
                    cv2.destroyAllWindows()
                    return False
# ############ end Face-recognitions login ############


def login(request):
    if 'USER' in request.session:
        return redirect('home')
    else:
        # Check if the data is Posted
        if (request.POST):
            # check if user exists
            check_user = User.objects.filter(
                email=request.POST['email'], password=request.POST['password'])

            if check_user:
                # check role of the user and add it to session
                if check_user[0].role == "medecin" and face_login(check_user[0].nom) == True:
                    request.session['USER'] = {
                        'id': check_user[0].id, 'email': check_user[0].email, 'username': check_user[0].username, 'role': check_user[0].role}
                    return redirect('home')
                elif check_user[0].role == "admin":
                    request.session['USER'] = {
                        'id': check_user[0].id, 'email': check_user[0].email, 'username': check_user[0].username, 'role': check_user[0].role}
                    return redirect('home')
                elif check_user[0].role == "patient":
                    request.session['USER'] = {
                        'id': check_user[0].id, 'email': check_user[0].email, 'username': check_user[0].username, 'role': check_user[0].role}
                    return redirect('home')
                else:
                    title = "Login"

                    message = [
                        'You are not allowed to login here!, you must make a face login.', 'danger']
                    return render(request, 'users/login.html', {'title': title, 'message': message})

            else:
                # User not found email or psss word incorect:
                title = "Login"
                message = ['email or psss incorect!', 'danger']
                return render(request, 'users/login.html', {'title': title, 'message': message})
        # if it's not Post method
        else:
            title = "Login"
            return render(request, 'users/login.html', {'title': title})
############ end Login to Session ###########


############ Sign Up to Session ############
def signup(request):
    if request.method == 'POST':
        username = request.POST['userName']
        first_name = request.POST['fName']
        last_name = request.POST['lName']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['password_confirm']

        cliniques = Clinique.objects.all()
        medecins = Medecin.objects.all()

        if password != confirm_password:
            title = "Sign Up"
            message = ['passwords not match!', 'danger']
            return render(request, 'users/signup.html', {"medecins": medecins, "cliniques": cliniques, 'title': title, 'message': message})

        if User.objects.filter(email=email).exists():
            title = "Sign Up"
            message = ['email already exists!', 'danger']
            return render(request, 'users/signup.html', {"medecins": medecins, "cliniques": cliniques, 'title': title, 'message': message})

        if User.objects.filter(username=username).exists():
            title = "Sign Up"
            message = ['username already exists!', 'danger']
            return render(request, 'users/signup.html', {"medecins": medecins, "cliniques": cliniques, 'title': title, 'message': message})

        user = Patient(
            username=username, nom=first_name, prenom=last_name, email=email, password=password)

        user.save()

        title = "Sign Up"
        message = ['Your account has been created successfully!', 'success']
        return render(request, 'users/signup.html', {"medecins": medecins, "cliniques": cliniques, 'message': message})

    else:
        cliniques = Clinique.objects.all()
        medecins = Medecin.objects.all()
        title = "Sign Up"
        return render(request, 'users/signup.html', {"medecins": medecins, "cliniques": cliniques})
############ end Sign Up ###########


def profile(request):
    if 'USER' in request.session:
        user = request.session['USER']
        # Fetch user information from the database based on the user's ID based on there role
        if user['role'] == "medecin":
            user_info = Medecin.objects.get(id=user['id'])
            return render(request, 'users/profile.html', {'user_info': user_info})
        elif user['role'] == "admin":
            user_info = Admin.objects.get(id=user['id'])
        elif user['role'] == "patient":
            user_info = Patient.objects.get(id=user['id'])
            return render(request, 'users/patient_profile.html', {'patient': user_info})

        else:
            user_info = None

        return render(request, 'users/profile.html', {'user_info': user_info})
    else:
        return redirect('login')


def medecin_details(request, id):
    medecin = Medecin.objects.get(id=id)
    return render(request, 'users/medecin_details.html', {'user_info': medecin})


def Host(request):
    title = "Host"
    return render(request, 'host/becam_host.html', {'title': title})

templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Section login -->
<section class="section section-lg pt-6 mt-5">
  <div class="container">
    <div class="row justify-content-center">
      {% if message %}
      <div class="col-md-8">
        <div
          class="alert alert-{{ message.1 }} alert-dismissible fade show"
          role="alert"
        >
          {{ message.0 }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
      </div>
      {% endif %}
      <div class="col-md-6">
        <div
          class="signin-inner bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5"
        >
          <div class="text-center mb-4">
            <h1 class="mb-0 h3">Sign in to our platform</h1>
          </div>
          <form action="" method="post" class="mt-4">
            {% csrf_token %}
            <div class="mb-3">
              <label for="email" class="form-label">Your Email</label>
              <input
                type="email"
                class="form-control"
                placeholder="example@company.com"
                name="email"
                required=""
              />
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Your Password</label>
              <input
                type="password"
                placeholder="Password"
                class="form-control"
                name="password"
                required=""
              />
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <div class="form-check">
                <input
                  class="form-check-input"
                  type="checkbox"
                  value=""
                  id="remember"
                />
                <label class="form-check-label" for="remember">Remember me</label>
              </div>
              <div>
                <a href="#" class="small text-right">Lost password?</a>
              </div>
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-primary">
                Sign in
              </button>
            </div>
          </form>
          <div class="mt-3 mb-4 text-center">
            <span class="fw-normal">or login with</span>
          </div>
          <div class="btn-wrapper my-4 text-center">
            <a
              href="#"
              class="btn btn-icon-only btn-pill btn-outline-primary me-2"
              aria-label="facebook button"
              title="facebook button"
              ><span aria-hidden="true" class="fab fa-facebook-f"></span> </a
            ><a
              href="#"
              class="btn btn-icon-only btn-pill btn-outline-primary me-2"
              aria-label="twitter button"
              title="twitter button"
              ><span aria-hidden="true" class="fab fa-twitter"></span>
            </a>
            <a
              href="#"
              class="btn btn-icon-only btn-pill btn-outline-primary"
              aria-label="github button"
              title="github button"
              ><span aria-hidden="true" class="fab fa-github"></span
            ></a>
          </div>
          <div class="dHere's the continuation of the HTML template with the remaining UI/UX design modifications:ivider text-center my-4">
            <span class="px-4 bg-white fw-normal"
              >Or login with credentials</span
            >
          <div class="d-flex justify-content-center align-items-center mt-4">
            <span class="fw-normal">Not registered?</span>
            <a href="{% url 'signup' %}" class="fw-bold text-primary ms-2">Create account</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/users/medecin_details.html
{% extends "base.html" %} {% load static %} {% block content %}
<!-- Section Profile -->
<section class="section section-profile mt-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body text-center">
            {% if user_info.image %}
            <img
              src="/{{ user_info.image }}"
              class="avatar img-fluid rounded-circle mb-3"
              alt="Avatar"
            />
            {% else %}
            <img
              src="/static/imgs/avatar.jpeg"
              class="avatar img-fluid rounded-circle mb-3"
              alt="Avatar"
            />
            {% endif %}
            <h3 class="mb-3">{{ user_info.prenom }} {{ user_info.nom }}</h3>
            <p class="text-muted">{{ user_info.role }}</p>
            <a href="#" class="btn btn-primary btn-block mb-4">Make Appointments</a>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6">
                <h4>About</h4>
                <p class="text-muted">{{ user_info.description }}</p>
              </div>
              <div class="col-sm-6">
                <h4>Contact Information</h4>
                <ul class="list-unstyled">
                  <li>
                    <i class="fas fa-envelope"></i>
                    <a href="mailto:{{ user_info.email }}"
                      >{{ user_info.email }}</a
                    >
                  </li>
                  <li><i class="fas fa-phone"></i> {{ user_info.tele }}</li>
                  <li>
                    <i class="fas fa-map-marker-alt"></i> {{ user_info.address}}
                  </li>
                </ul>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-6">
                <h4>Specialization</h4>
                <p class="text-muted">{{ user_info.specialite }}</p>
              </div>
              <div class="col-sm-6">
                <h4>Working Hours</h4>
                <ul class="list-unstyled">
                  <li>Monday: 9:00 AM - 5:00 PM</li>
                  <li>Tuesday: 9:00 AM - 5:00 PM</li>
                  <li>Wednesday: 9:00 AM - 5:00 PM</li>
                  <li>Thursday: 9:00 AM - 5:00 PM</li>
                  <li>Friday: 9:00 AM - 1:00 PM</li>
                  <li>Saturday: Closed</li>
                  <li>Sunday: Closed</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/users/patient_profile.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-6">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h1 class="mt-5 mb-4">Patient Information</h1>
        

        <div class="card ">
          <div class="card-body">
            <h5 class="card-title">Personal Information</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Name:</strong> {{ patient.nom }} {{ patient.prenom }}</li>
              <li class="list-group-item"><strong>Username:</strong> {{ patient.username }}</li>
              <li class="list-group-item"><strong>Email:</strong> {{ patient.email }}</li>
              <li class="list-group-item"><strong>Address:</strong> {{ patient.address }}</li>
              <li class="list-group-item"><strong>Sex:</strong> {{ patient.get_sexe_display }}</li>
              <li class="list-group-item"><strong>Phone Number:</strong> {{ patient.tele }}</li>
              <li class="list-group-item"><strong>Date of Birth:</strong> {{ patient.date_naissance }}</li>
            </ul>
          </div>
        </div>
        <div class="card mt-4">
          <div class="card-body">
            <h5 class="card-title">Medical Information</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Medical ID:</strong> {{ patient.id }}</li>
              <!-- Add more medical information fields as needed -->
              <li class="list-group-item"><strong>Rendezvous:</strong>
                <ul>
                  {% for rendezvous in patient.patient.all %}
                    <li>Date: {{ rendezvous.date }}, Time: {{ rendezvous.time }}, Clinique: {{ rendezvous.clinique.nom }}</li>
                  {% endfor %}
                </ul>
              </li>

              <li class="list-group-item"><strong>Prescriptions:</strong>
                <ul>
                  {% for prescription in patient.prescription.all %}
                    <li>Medicament: {{ prescription.medicament.nom }}, Dose: {{ prescription.dose }}, Date: {{ prescription.date }}</li>
                  {% endfor %}
                </ul>

                </li>

                <li class="list-group-item"><strong>Consultations:</strong>
                  <ul>
                    {% for consultation in patient.consultation.all %}
                      <li>Date: {{ consultation.date }}, Time: {{ consultation.time }}, Clinique: {{ consultation.clinique.nom }}</li>
                    {% endfor %}
                  </ul>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/profile.html
{% extends "base.html" %} {% load static %} {% block content %}
<!-- Section Profile -->
<section class="section section-profile mt-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body text-center">
            {% if user_info.image %}
            <img
              src="/{{ user_info.image }}"
              class="avatar img-fluid rounded-circle mb-3"
              alt="Avatar"
            />
            {% else %}
            <img
              src="/static/imgs/avatar.jpeg"
              class="avatar img-fluid rounded-circle mb-3"
              alt="Avatar"
            />
            {% endif %}
            <h3 class="mb-3">{{ user_info.prenom }} {{ user_info.nom }}</h3>
            <p class="text-muted">{{ user_info.role }}</p>
            <a href="#" class="btn btn-primary btn-block mb-4">Edit Profile</a>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6">
                <h4>About</h4>
                <p class="text-muted">{{ user_info.description }}</p>
              </div>
              <div class="col-sm-6">
                <h4>Contact Information</h4>
                <ul class="list-unstyled">
                  <li>
                    <i class="fas fa-envelope"></i>
                    <a href="mailto:{{ user_info.email }}"
                      >{{ user_info.email }}</a
                    >
                  </li>
                  <li><i class="fas fa-phone"></i> {{ user_info.tele }}</li>
                  <li>
                    <i class="fas fa-map-marker-alt"></i> {{ user_info.address}}
                  </li>
                </ul>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-6">
                <h4>Specialization</h4>
                <p class="text-muted">{{ user_info.specialite }}</p>
              </div>
              <div class="col-sm-6">
                <h4>Working Hours</h4>
                <ul class="list-unstyled">
                  <li>Monday: 9:00 AM - 5:00 PM</li>
                  <li>Tuesday: 9:00 AM - 5:00 PM</li>
                  <li>Wednesday: 9:00 AM - 5:00 PM</li>
                  <li>Thursday: 9:00 AM - 5:00 PM</li>
                  <li>Friday: 9:00 AM - 1:00 PM</li>
                  <li>Saturday: Closed</li>
                  <li>Sunday: Closed</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}{% load static %} {% block content %}

<!-- Section signup -->
<section class="section section-lg pt-6 mt-5">
  <div class="container">
    {% if message %}
    <div class="row justify-content-center">
      <div class="col-auto m-3">
        <div
          class="toast bg-primary text-white fade show"
          role="alert"
          aria-live="assertive"
          aria-atomic="true"
        >
          <div class="toast-header">
            <span class="far fa-comments me-2"></span>
            <strong class="me-auto">Messsage</strong>
            <small>{{ message.1 }}</small>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="toast"
              aria-label="Close"
            ></button>
          </div>
          <div class="toast-body">{{ message.0 }}</div>
        </div>
      </div>
    </div>
    {% endif %}
    <div class="row justify-content-center">
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div
          class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500"
        >
          <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h3">Create an account</h1>
          </div>
          <form action="" method="post">
            {% csrf_token %}
            <!-- Form -->
            <div class="form-group mb-4">
              <label for="email">Username</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon3"
                  ><span
                    ><svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-person"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"
                      /></svg></span
                ></span>
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="userName"
                  required=""
                />
              </div>
            </div>
            <!-- End of Form -->

            <!-- Form -->
            <div class="form-group mb-4">
              <label for="email">First Name</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon3"
                  ><span class="far fa-user-circle"></span
                ></span>
                <input
                  type="text"
                  class="form-control"
                  placeholder="First Name"
                  name="fName"
                  required=""
                />
              </div>
            </div>
            <!-- End of Form -->

            <!-- Form -->
            <div class="form-group mb-4">
              <label for="email">Last Name</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon3"
                  ><span class="far fa-user-circle"></span
                ></span>
                <input
                  type="text"
                  class="form-control"
                  placeholder="Last Name"
                  name="lName"
                  required=""
                />
              </div>
            </div>
            <!-- End of Form -->

            <!-- Form -->
            <div class="form-group mb-4">
              <label for="email">Your Email</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon3"
                  ><span class="fas fa-envelope"></span
                ></span>
                <input
                  type="email"
                  class="form-control"
                  placeholder="example@company.com"
                  name="email"
                  required=""
                />
              </div>
            </div>
            <!-- End of Form -->
            <div class="form-group">
              <!-- Form -->
              <div class="form-group mb-4">
                <label for="password">Your Password</label>
                <div class="input-group">
                  <span class="input-group-text" id="basic-addon4"
                    ><span class="fas fa-unlock-alt"></span
                  ></span>
                  <input
                    type="password"
                    placeholder="Password"
                    class="form-control"
                    id="password"
                    name="password"
                    required=""
                  />
                </div>
              </div>
              <!-- End of Form -->
              <!-- Form -->
              <div class="form-group mb-4">
                <label for="password_confirm">Confirm Password</label>
                <div class="input-group">
                  <span class="input-group-text" id="basic-addon5"
                    ><span class="fas fa-unlock-alt"></span
                  ></span>
                  <input
                    type="password"
                    placeholder="Confirm Password"
                    class="form-control"
                    name="password_confirm"
                    required=""
                  />
                </div>
              </div>
              <!-- End of Form -->
              <div class="form-check mb-4">
                <input
                  class="form-check-input"
                  type="checkbox"
                  value=""
                  id="terms"
                  required=""
                />
                <label class="form-check-label" for="terms">
                  I agree to the <a href="#">terms and conditions</a>
                </label>
              </div>
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-primary">Sign up</button>
            </div>
          </form>
          <div class="mt-3 mb-4 text-center">
            <span class="fw-normal">or</span>
          </div>
          <div class="btn-wrapper my-4 text-center">
            <a
              href="#"
              class="btn btn-icon-only btn-pill btn-outline-gray-300 text-facebook me-2"
              aria-label="facebook button"
              title="facebook button"
            >
              <span aria-hidden="true" class="fab fa-facebook-f"></span>
            </a>
            <a
              href="#"
              class="btn btn-icon-only btn-pill btn-outline-gray-300 text-twitter me-2"
              aria-label="twitter button"
              title="twitter button"
            >
              <span aria-hidden="true" class="fab fa-twitter"></span>
            </a>
            <a
              href="#"
              class="btn btn-icon-only btn-pill btn-outline-gray-300 text-facebook"
              aria-label="github button"
              title="github button"
            >
              <span aria-hidden="true" class="fab fa-github"></span>
            </a>
          </div>
          <div class="d-flex justify-content-center align-items-center mt-4">
            <span class="fw-normal">
              Already have an account?
              <a href="{% url 'login' %}" class="fw-bold text-underline"
                >Login here</a
              >
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}